doctrine:
    dbal:
        # configure these for your database server
#        driver: 'pdo_mysql'
#        server_version: '5.7'
#        charset: utf8mb4
#         default_table_options:
#            charset: utf8mb4
#            collate: utf8mb4_unicode_ci
#            host: 127.0.0.1
#            port: 3306
#        url: '%env(resolve:DATABASE_URL)%'
        default_connection: template
        connections:
            template:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            ressources:
                # configure these for your database server
                url: '%env(resolve:DATABASE_SECONDARY_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
    orm:
        default_entity_manager: template
        entity_managers:
            template:
                connection: template
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Template'
                        prefix: 'App\Entity\Template'
                        alias: Template

            ressources:
                connection: ressources
                mappings:
                    AddOn:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/TemplateRessources'
                        prefix: 'App\Entity\TemplateRessources'
                        alias: TemplateRessources

