# config/packages/doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(DATABASE_TEMPLATE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            templateressources:
                # configure these for your database server
                url: '%env(DATABASE_TEMPLATERESSOURCES_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Template:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Template'
                        prefix: 'App\Entity\Template'
                        alias: Template
            templateressources:
                connection: templateressources
                mappings:
                    TemplateRessources:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/TemplateRessources'
                        prefix: 'App\Entity\TemplateRessources'
                        alias: TemplateRessources

